### ISSUE TITLE
SMART Centre group

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/project-nominations#10]
### Which project should absolutely be on Giveth?

SMART Centre group

### Please provide the project's Twitter/Discord/Website/Email.

https://smartcentregroup.com/

### Who are you?

https://twitter.com/mettoddo

### How would you describe the project in one sentence?

Simple, Market based, Affordable and Repairable Technologies deployed through training and supply chain development

### Why are you convinced by this project?

Their impact speaks by itself: https://smartcentregroup.com/wp-content/uploads/2022/06/SMART-Centres-Vrs.-05-05-2022.pdf

### If you have more information about the project, 
you can enter it here.

Background SMART Centres train the local private sector in developing countries in Simple, Market-based, Affordable, Repairable Technologies, (SMARTechs) for water and sanitation. Examples are different manual well drilling technologies, EMAS and rope pumps, solar pumps, water storage tanks, groundwater tube recharge, household water filters, SaTopan latrines, and others. SMART Centres are hosted by a local NGO or government and train in technical aspects like drilling, producing drill sets and pumps, installation and maintenance. There is also training in business skills like management and marketing. Trainees are selected based on motivation, skills and entrepreneurship. The educational level of a person is less a condition. The experience has been that those with limited education are sometimes the most successful and hard working. SMART Centres are member of the SMART Centre Group and have a kind of a franchise model. To become member of the group conditions apply. See document on membership. The host organization of the SMART Centre Group is the social enterprise MetaMeta based in Wageningen, Netherlands. Vision and actions The vision of SMART Centres in short is “water, sanitation and food for all”. The action to reach this is the SMART approach, a combination of SMARTechs and a focus on aspects like: • Household water filters. As a first and very cost-effective option for safe drinking water • Local production. Where possible produce drill sets, pumps etc. with local materials • Family Based Management. A family responsible for management instead of a community • Well clubs. Families drilling their own well with guidance of a trained driller • Supported self-supply. Stimulate families to invest in their own well, eventually with subsidy The SMART approach creates a sustainable commercial supply chain of affordable water and sanitation technologies. For instance when boreholes can be made with manual drilling tools, small communities can be reached where machine drilling rigs cannot enter or where they are too expensive. If hand pumps can be produced locally they also become affordable for families. For example of the 200.000 EMAS and rope pumps worldwide over 70% are self-supply so paid by families themselves. The local production guarantees availability of skills and spare parts, essential for maintenance and reduces the need for import. SMART Centres help; not with a fish but with a fishing rod and ....skills to produce the fishing rod. The long-term goal is to “disappear”, for instance by transferring knowledge of SMARTechs on to national vocational education systems. Cost of SMART Centres The cost to start and run a SMART centre depends a lot on the situation. For instance if there is not yet an infrastructure the building and contents of a basic training workshop with tools, jigs for production, installation of a demonstration field etc. will cost 50.000 to 150.000 USD. To run a SMART centre requires at least a manager/ trainer and eventually additional staff for administration. Also funds are needed for running a (small) office, transport, training sessions, installation of SMARTechs in show case areas, promotion etc. Cost of these range from 70.000 to 250.000 USD / year. The impact of the SMART Centres Results of the existing SMART Centres until now are: • 12.000+ rope pumps installed. Over 60% self-supply (100% investment by the user) • 4.000+ wells drilled mostly for subsidised communal water supply systems • 80 small companies established, employing 200 technicians • 1 million+ people with water access • Actions go on after training stop, companies are working independently.

### Are you affiliated with this project? 

true

### Do you own GIV tokens?

true

**Comment by melodysongq** [comment]
Mettoto is a current project owner for Njomba Academy.  We can reach out to him directly to engage this project.

**Comment by SnakeGH** [comment]
Added them to the CRM and made initial outreach.
