### ISSUE TITLE
National Butterfly Center

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/project-nominations#17]
### Which project should absolutely be on Giveth?

National Butterfly Center

### Please provide the project's Twitter/Discord/Website/Email.

https://twitter.com/NatButterflies || https://nationalbutterflycenter.org/ || nbc@nationalbutterflycenter.org

### Who are you?

Discord: logonaut.eth#9437 || Twitter: logonaut || giveth.fantastically@simplelogin.com

### How would you describe the project in one sentence?

The National Butterfly Center in Mission, Texas, is a 100-acre wildlife center and native species botanical garden that comprises the North American Butterfly Association’s flagship location and a primary focus of its efforts aimed at educating the public about the value of biodiversity, the beauty of the natural world, the wonder of butterflies, particularly, and the powerful role they play in maintaining healthy ecosystems and sustainable food resources; the center has made national news for its legal battle against builders of the border wall and for the threats it has received from QAnon-aligned conspiracy theorists.

### Why are you convinced by this project?

This is a project that is local to my community in deep South Texas near the Mexico border, in one of the poorest regions of the United States. The center is aligned with the highest ideals of web3 optimism, but to the best of my knowledge has not yet connected with its potential regen allies in web3. Its mission, vision, and location at an important crossroads in a major bird and butterfly migration corridor in the Americas attracts visitors from all over the world. It routinely conducts community education and outreach — all with an already modest budget that is stretched thinner by its legal battle against border wall builders and its need for heightened security amid threats from right-wing conspiracy theorists.

### If you have more information about the project, 
you can enter it here.

Public goods include education, biodiversity, pollinator conservation, renewable energy generation, freedom of movement advocacy, property rights advocacy, due process advocacy, and resistance against authoritarian policy by those with a monopoly on violence. National Butterfly Center executive director Marianna Treviño-Wright is the public face of the center and its most outspoken advocate. Max Muñoz is the center’s director of operations. The center operates under the umbrella of the North American Butterfly Association, a 501(c)(3) charity: https://www.guidestar.org/profile/13-3689481 || https://www.charitynavigator.org/ein/133689481

### Are you affiliated with this project? 

false

### Do you own GIV tokens?

true

**Comment by melodysongq** [comment]
This sounds like a great project.  Should be assigned for outreach.

**Comment by SnakeGH** [comment]
I have made initial contact and have had an initial meeting with the handler.

**Comment by SnakeGH** [comment]
Marc and his wife are working to secure a meeting with the Executive Director (Marianna)  of the NBC for Giveth (me)
