### ISSUE TITLE
Tanzania Open Science Hardware (TanzaniaOSH)

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/project-nominations#6]
### Which project should absolutely be on Giveth?

Tanzania Open Science Hardware (TanzaniaOSH)

### Please provide the project's Twitter/Discord/Website/Email.

tanzania@africaosh.com

### Who are you?

sangavalerian@btech.co.tz

### How would you describe the project in one sentence?

The Tanzanian Open Source Community

### Why are you convinced by this project?

Open Acces towards realizing sustainable local solutions.

### Are you affiliated with this project? 

true

### Do you own GIV tokens?

false

**Comment by SnakeGH** [comment]
Added them to our CRM and made outreach

**Comment by SnakeGH** [comment]
As of today no response from them
