### ISSUE TITLE
Tadeh

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/project-nominations#9]
### Which project should absolutely be on Giveth?

Tadeh

### Please provide the project's Twitter/Discord/Website/Email.

https://tadeh.org/en/

### Who are you?

Mettodo#7010

### How would you describe the project in one sentence?

Training on water self supply with simple tech

### Why are you convinced by this project?

I met the people involved and I have seen how great their simple technologies are

### If you have more information about the project, 
you can enter it here.

They collaborate with Emas Bolivia https://www.google.com/url?sa=t&source=web&rct=j&url=https://m.youtube.com/user/EMASbolivia/videos&ved=2ahUKEwiWqvXZifH4AhVag_0HHcIWCR4QFnoECAkQAQ&usg=AOvVaw2-LsczH6-fYaozdACx589E

### Are you affiliated with this project? 

false

### Do you own GIV tokens?

true

**Comment by SnakeGH** [comment]
added them to the CRM, made the outreach and heard back from them about setting up a meeting

**Comment by SnakeGH** [comment]
Connected with Jaime from their team and working on times to set up a video call
